# Generated by Django 5.2.7 on 2025-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True),
        ),
    ]
