# Generated by Django 5.2.7 on 2025-11-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_cliente_options_alter_cliente_estado_and_more'),
        ('administracion', '0005_alter_cliente_estado'),
    ]

    operations = [
    ]
