# Generated by Django 5.2.7 on 2025-11-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_cliente_estado_alter_cliente_razon_social_and_more'),
        ('administracion', '0006_merge_20251109_2322'),
    ]

    operations = [
    ]
