# Generated by Django 5.2.7 on 2025-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_cliente_estado_alter_cliente_razon_social_and_more'),
        ('administracion', '0009_add_venta_detalleventa'),
    ]

    operations = [
    ]
