# Generated by Django 5.2.7 on 2025-10-29 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meses_garantia', models.PositiveIntegerField(default=12)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='catalogo.marca')),
            ],
            options={
                'verbose_name': 'Catálogo de Producto',
                'verbose_name_plural': 'Catálogos de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=100, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('en_reparacion', 'En Reparación'), ('dado_de_baja', 'Dado de Baja'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('disponible', 'Disponible')], default='disponible', max_length=15)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('Catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.catalogo')),
            ],
            options={
                'verbose_name': 'Ítem de Producto (Serializado)',
                'verbose_name_plural': 'Ítems de Productos (Serializados)',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
