# Generated by Django 5.2.7 on 2025-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Catalogo',
            new_name='catalogo',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('dado_de_baja', 'Dado de Baja'), ('en_reparacion', 'En Reparación')], default='disponible', max_length=15),
        ),
    ]
