# Generated by Django 5.2.7 on 2025-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('dado_de_baja', 'Dado de Baja'), ('disponible', 'Disponible'), ('en_reparacion', 'En Reparación'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=15),
        ),
    ]
