# Generated by Django 5.2.7 on 2025-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('en_reparacion', 'En Reparación'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('dado_de_baja', 'Dado de Baja'), ('disponible', 'Disponible')], default='disponible', max_length=15),
        ),
    ]
