# Generated by Django 5.2.7 on 2025-10-30 22:00
# Generated by Django 5.2.7 on 2025-11-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_catalogo_producto_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='catalogo',
            field=models.ForeignKey(db_column='Catalogo_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.catalogo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('en_reparacion', 'En Reparación'), ('vendido', 'Vendido'), ('dado_de_baja', 'Dado de Baja'), ('reservado', 'Reservado'), ('disponible', 'Disponible')], default='disponible', max_length=15),
        ),
    ]
