# Generated by Django 5.2.7 on 2025-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_catalogo_estado_alter_producto_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('disponible', 'Disponible'), ('vendido', 'Vendido'), ('en_reparacion', 'En Reparación'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=15),
        ),
    ]
