# Generated by Django 5.2.7 on 2025-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_catalogo_estado_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('dado_de_baja', 'Dado de Baja'), ('vendido', 'Vendido'), ('en_reparacion', 'En Reparación'), ('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=15),
        ),
    ]
