# Generated by Django 5.2.6 on 2025-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('dado_de_baja', 'Dado de Baja'), ('en_reparacion', 'En Reparación'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
