# Generated by Django 5.2.6 on 2025-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_add_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('vendido', 'Vendido'), ('en_reparacion', 'En Reparación'), ('disponible', 'Disponible'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=15),
        ),
    ]
