# Generated by Django 5.2.6 on 2025-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('disponible', 'Disponible'), ('en_reparacion', 'En Reparación'), ('vendido', 'Vendido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=15),
        ),
    ]
