# Generated by Django 5.2.7 on 2025-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_fecha_venta_alter_catalogo_estado_and_more'),
        ('catalogo', '0008_add_cart_item'),
    ]

    operations = [
    ]
