# Generated by Django 5.2.6 on 2025-11-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_merge_20251111_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('dado_de_baja', 'Dado de Baja'), ('disponible', 'Disponible'), ('en_reparacion', 'En Reparación'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
