# Generated by Django 5.2.6 on 2025-11-10 23:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_producto_estado'),
        ('ventas', '0002_add_venta_detalleventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Envío'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.TextField(default='Por definir', verbose_name='Dirección de Entrega'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='ventas_detalle_venta',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas_venta',
        ),
        # Cart y CartItem ya existen en migraciones anteriores
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='BOB', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('proveedor', models.CharField(help_text='Ej: Stripe, PayPal, Transferencia Bancaria, etc.', max_length=100, verbose_name='Proveedor de Pago')),
                ('transaccion_id', models.CharField(help_text='ID único proporcionado por el proveedor de pago', max_length=255, unique=True, verbose_name='ID de Transacción')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'ventas_pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
